[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --baud 1000000"
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[profile.release]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
codegen-units = 1
lto = false

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32c3"
ESP_IDF_VERSION = "v5.2.1"

ESP_IDF_PATH_ISSUES = "warn" # fix builds on Windows https://github.com/esp-rs/esp-idf-sys/issues/252

ESP_IDF_SDKCONFIG_DEFAULTS = { value = "sdkconfig.defaults" }
